apiVersion: v1
kind: Service
metadata:
  name: kubernetesdemo-api-service
  labels:
    app: kubernetesdemo-api
spec:
  selector:
    app: kubernetesdemo-api
  ports:
    - protocol: TCP
      port: 3000 # Service Port
      targetPort: 3000 # Container Port
  type: NodePort # Change to LoadBalancer if running in cloud
